package com.smartcity.dao;

import com.smartcity.domain.Organization;
import com.smartcity.exceptions.DbOperationException;
import com.smartcity.exceptions.NotFoundException;
import com.smartcity.mapper.OrganizationMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Repository;

import javax.sql.DataSource;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public class OrganizationDaoImpl implements OrganizationDao {

    private static final Logger logger = LoggerFactory.getLogger(OrganizationDaoImpl.class);
    private JdbcTemplate jdbcTemplate;

    @Autowired
    public OrganizationDaoImpl(DataSource source) {
        jdbcTemplate = new JdbcTemplate(source);
    }

    @Override
    public Organization create(Organization organization) {
        try {
            GeneratedKeyHolder holder = new GeneratedKeyHolder();
            LocalDateTime currDate = LocalDateTime.now();
            organization.setCreatedDate(currDate);
            organization.setUpdatedDate(currDate);
            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(Queries.SQL_ORGANIZATION_CREATE,
                        Statement.RETURN_GENERATED_KEYS);
                ps.setString(1, organization.getName());
                ps.setString(2, organization.getAddress());
                ps.setObject(3, organization.getCreatedDate());
                ps.setObject(4, organization.getUpdatedDate());
                return ps;
            }, holder);
            organization.setId(Optional.ofNullable(holder.getKey()).map(Number::longValue)
                    .orElseThrow(() -> new DbOperationException("Create organization error: AutoGeneratedKey = null")));
            return organization;
        } catch (Exception e) {
            logger.error("Can't create organization:{}. Error:{}", organization, e.getMessage());
            throw new DbOperationException("Can't create organization: " + organization +
                    "Create organization Dao method error:" + e);
        }
    }

    @Override
    public Organization get(Long id) {
        Organization organization;
        try {
            organization = this.jdbcTemplate.queryForObject(Queries.SQL_ORGANIZATION_GET,
                    new OrganizationMapper(), id);
            return organization;
        } catch (EmptyResultDataAccessException erda) {
            logger.error("Can't find organization by id:{}. Error:{}.", id, erda.getMessage());
            throw new NotFoundException("Can't find organization by id=" + id);
        } catch (Exception e) {
            logger.error("Can't get organization by id={}. Error: {}", id, e.getMessage());
            throw new DbOperationException("Can't get organization by id = " + id +
                    "Get organization Dao method error:" + e);
        }
    }

    @Override
    public Organization update(Organization organization) {
        int rowsAffected;
        organization.setUpdatedDate(LocalDateTime.now());
        try {
            rowsAffected = jdbcTemplate.update(Queries.SQL_ORGANIZATION_UPDATE,
                    organization.getName(),
                    organization.getAddress(),
                    organization.getUpdatedDate(),
                    organization.getId());
        } catch (Exception e) {
            logger.error("Can't update organization:{}. Error:{}", organization, e.getMessage());
            throw new DbOperationException("Can't update organization: " + organization +
                    "Update organization Dao method error:" + e);
        }
        if (rowsAffected < 1) {
            logger.error("Can't find organization: {}", organization);
            throw new NotFoundException("Can't find organization: " + organization);
        } else return organization;
    }

    @Override
    public boolean delete(Long id) {
        int rowsAffected;
        try {
            rowsAffected = jdbcTemplate.update(Queries.SQL_ORGANIZATION_DELETE, id);
        } catch (Exception e) {
            logger.error("Can't delete organization by id={}. Error: {}", id, e.getMessage());
            throw new DbOperationException("Can't delete organization by id = " + id +
                    "Delete organization Dao method error:" + e);
        }
        if (rowsAffected < 1) {
            logger.error("Can't find organization by id = {}", id);
            throw new NotFoundException("Can't find organization by id=" + id);
        } else return true;
    }

    @Override
    public List<Organization> getAll() {
        try {
            return this.jdbcTemplate.query(Queries.SQL_ORGANIZATION_GET_ALL, new OrganizationMapper());
        } catch (Exception e) {
            logger.error("Can't get all organizations. Error:{}", e.getMessage());
            throw new DbOperationException("Can't get all organizations. GetAll organization Dao method error:" + e);
        }
    }

    class Queries {
        static final String SQL_ORGANIZATION_CREATE = "INSERT INTO Organizations(name, address, created_date," +
                " updated_date) values(?,?,?,?)";
        static final String SQL_ORGANIZATION_GET = "SELECT * FROM Organizations where id = ?";
        static final String SQL_ORGANIZATION_UPDATE = "UPDATE Organizations set name = ?, address = ?," +
                " updated_date = ? where id = ?";
        static final String SQL_ORGANIZATION_DELETE = "DELETE FROM Organizations where id = ?";
        static final String SQL_ORGANIZATION_GET_ALL = "Select * from Organizations";
    }
}

